name: Compliance Test CI / CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Mosquitto Broker
        run: |
          sudo apt-add-repository ppa:mosquitto-dev/mosquitto-ppa -y
          sudo apt-get update -y
          sudo apt install -y mosquitto mosquitto-clients
          mosquitto &
          sleep 5

      - name: Clone Compliance Test and Install Dependencies
        run: |
          git clone https://github.com/device-automation-bus/dab-compliance-suite.git
          pip install -r dab-compliance-suite/requirements.txt
          npm install

      - name: Run Bridge and Onboard Device
        run: |
          node src/index.js &
          sleep 3
          mosquitto_pub -t dab/bridge/template/add-device -m '{ "skipValidation": true, "ip": "sample-ip.com", "dabDeviceId": "custom-dab-device-id"}' -D publish response-topic "my/response/topic"
          timeout 30 python dab-compliance-suite/main.py --output test/ci_cd_compliance_result.json -I custom-dab-device-id -b 127.0.0.1

      - run: node test/simple_json_compare.cjs test/ci_cd_compliance_result.json test/expected_compliance_result.json logs
